// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpyUsMwymhDX9mT4LLuFZT6TekiUwLV9Y',
    appId: '1:271123722450:android:4e54972f31fcd184bffd0b',
    messagingSenderId: '271123722450',
    projectId: 'barbearia-dono-app',
    storageBucket: 'barbearia-dono-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcaDXEVOEnHb31uqUz6HToOiuJbJp_xA8',
    appId: '1:271123722450:ios:1ed2b5ae91e9888ebffd0b',
    messagingSenderId: '271123722450',
    projectId: 'barbearia-dono-app',
    storageBucket: 'barbearia-dono-app.firebasestorage.app',
    androidClientId: '271123722450-mqn5dm20po8tn95oigrgm7ak0ddvgk43.apps.googleusercontent.com',
    iosClientId: '271123722450-qfq2rd2dchgp4tbo89va2h2k9nl6fku9.apps.googleusercontent.com',
    iosBundleId: 'com.example.barbeariaApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADN3zG0Am6D-yNhEOS_5eNjAjuRlqdDNY',
    appId: '1:271123722450:web:980e4e6e480a08bbbffd0b',
    messagingSenderId: '271123722450',
    projectId: 'barbearia-dono-app',
    authDomain: 'barbearia-dono-app.firebaseapp.com',
    storageBucket: 'barbearia-dono-app.firebasestorage.app',
    measurementId: 'G-J9YM3D2JPS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADN3zG0Am6D-yNhEOS_5eNjAjuRlqdDNY',
    appId: '1:271123722450:web:ebafc2bab7dfd601bffd0b',
    messagingSenderId: '271123722450',
    projectId: 'barbearia-dono-app',
    authDomain: 'barbearia-dono-app.firebaseapp.com',
    storageBucket: 'barbearia-dono-app.firebasestorage.app',
    measurementId: 'G-W3SCN7T6ZY',
  );

}